{{- range .Values.django.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "jenny.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "jenny.labels" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{ toYaml $.Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: jenny
  annotations:
{{- if $.Values.commonAnnotations }}
{{- toYaml $.Values.commonAnnotations | nindent 4 }}
{{- end }}
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      labels: {{- include "jenny.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: django
    spec:
      {{- include "django.imagePullSecrets" $ | nindent 6 }}
      containers:
        - name: django-{{ .name }}
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            {{- include "jenny.envs" $ | nindent 12 }}
          command: {{ .command | toJson }}
          {{- if $.Values.resources }}
          resources: {{ toYaml $.Values.resources | nindent 12 }}
          {{- end }}
          {{- if $.Values.persistence.enabled }}
          volumeMounts:
            - name: {{ $.Values.volumes.static.name }}
              mountPath: {{ $.Values.volumes.static.mountPath }}
            - name: {{ $.Values.volumes.media.name }}
              mountPath: {{ $.Values.volumes.media.mountPath }}
      volumes:
        - name: {{ $.Values.volumes.static.name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.volumes.static.claimName }}
        - name: {{ $.Values.volumes.media.name }}
          persistentVolumeClaim:
            claimName: {{ $.Values.volumes.media.claimName }}
          {{- end }}
      restartPolicy: Never
{{- end }}
