apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "django.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: django
  {{- if .Values.commonAnnotations }}
  annotations: {{ toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "django.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: django
  template:
    metadata:
      labels: {{- include "django.labels" . | nindent 8 }}
        app.kubernetes.io/component: django
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec: {{- include "django.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels: {{- include "django.selectorLabels" . | nindent 20 }}
                    app.kubernetes.io/component: django
                namespaces: 
                  - {{ .Release.Namespace | quote }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: DB_HOST
              value: {{ include "django.fullname" . }}-postgresql
            - name: DB_NAME
              value: {{ .Values.databaseName }}
            - name: DB_PORT
              value: {{ .Values.databasePort | quote }}
            - name: DJANGO_CONFIGURATION
              value: {{ .Values.appDjangoConfiguration }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.appDjangoSettingsModule }}
          envFrom:
            - secretRef:
                name: {{ include "django.fullname" . }}
            - configMapRef:
                name: {{ include "django.fullname" . }}-dotenv
          {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
          {{- end }}
          {{- if .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.extraEnvVarsCM }}
          {{- end }}
          {{- if .Values.customLivenessProbe }}
          livenessProbe: {{- toYaml .Values.customLivenessProbe | nindent 12 }}
          {{ else }}
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe.path }}
              port: {{ .Values.service.port }}
              httpHeaders:
                - name: Host
                  value: "{{ include  "django.host" .   }}"
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodeSeconds }}
          {{- end }}
          {{- if .Values.customReadinessProbe }}
          readinessProbe: {{- toYaml .Values.customReadinessProbe | nindent 12 }}
          {{ else }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.port }}
              httpHeaders:
                - name: Host
                  value: "{{ include "django.host" .   }}"
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodeSeconds }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
