{{- if .Values.appDjangoMigrate }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django.fullname" . }}-dbmigrate
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "django.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: django
  annotations:
{{- if .Values.commonAnnotations }}
{{- toYaml .Values.commonAnnotations | nindent 4 }}
{{- end }}
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      labels: {{- include "django.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: django
    spec: {{- include "django.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: django-dbmigrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ include "django.fullname" . }}-postgresql
            - name: DB_NAME
              value: {{ .Values.databaseName }}
            - name: DB_PORT
              value: {{ .Values.databasePort | quote }}
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ include "django.host" . }}
            - name: DJANGO_CONFIGURATION
              value: {{ .Values.appDjangoConfiguration }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.appDjangoSettingsModule }}
          envFrom:
            - configMapRef:
                name: {{ include "django.fullname" . }}-dotenv
            - secretRef:
                name:  {{ include "django.fullname" . }}
          {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
          {{- end }}
          command: ["python", "manage.py", "migrate"]
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
      restartPolicy: Never
{{- end }}