apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "django.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: django
  annotations: 
{{- if .Values.commonAnnotations }}
{{- toYaml .Values.commonAnnotations | nindent 4 }}
{{- end }}
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "0"
data: 
  {{- range .Values.djangoAppSecrets }}
  {{ .key }}: {{ .value | b64enc }}
  {{- end }}

