apiVersion: v1
kind: Service
metadata:
  name: {{ include "django.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "django.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{ toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: django
  {{- if .Values.commonAnnotations }}
  annotations: {{ toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: tcp-django
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector: {{- include "django.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: django
